"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PR_DESCRIPTION = exports.ACTION_URL = exports.BLOCKED_PROJECTS = exports.ALLOWED_PROJECTS = exports.GITHUB_PAT = exports.ASANA_PAT = exports.ASANA_SECRET = exports.COMMENT_TEXT = void 0;
exports.COMMENT_TEXT = "comment-text";
exports.ASANA_SECRET = "asana-secret";
exports.ASANA_PAT = "asana-pat";
exports.GITHUB_PAT = "github-pat";
exports.ALLOWED_PROJECTS = "allowed-projects";
exports.BLOCKED_PROJECTS = "blocked-projects";
exports.ACTION_URL = "action-url";
exports.PR_DESCRIPTION = "pr-description";
