"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LABELS_URL = exports.REQUESTED_REVIEWRS_URL = exports.REVIEWS_URL = exports.ISSUES_URL = exports.PULLS_URL = exports.REPOS_URL = exports.BASE_GITHUB_URL = exports.ADD_TASK_URL = exports.ADD_FOLLOWERS_URL = exports.SUBTASKS_URL = exports.STORIES_URL = exports.SECTIONS_URL = exports.TASKS_URL = exports.PROJECTS_URL = exports.BASE_ASANA_URL = exports.RETRY_DELAY = exports.RETRIES = exports.ACTION_URL = exports.BASE_URL = void 0;
exports.BASE_URL = "https://github.integrations.asana.plus/custom/v1";
exports.ACTION_URL = "actions/comment";
exports.RETRIES = 3;
exports.RETRY_DELAY = 1000;
exports.BASE_ASANA_URL = "https://app.asana.com/api/1.0";
exports.PROJECTS_URL = "/projects/";
exports.TASKS_URL = "/tasks/";
exports.SECTIONS_URL = "/sections/";
exports.STORIES_URL = "/stories/";
exports.SUBTASKS_URL = "/subtasks?opt_fields=completed,resource_subtype,assignee,created_by,name";
exports.ADD_FOLLOWERS_URL = "/addFollowers";
exports.ADD_TASK_URL = "/addTask";
exports.BASE_GITHUB_URL = "https://api.github.com/";
exports.REPOS_URL = "/repos/";
exports.PULLS_URL = "/pulls/";
exports.ISSUES_URL = "/issues/";
exports.REVIEWS_URL = "/reviews";
exports.REQUESTED_REVIEWRS_URL = "/requested_reviewers";
exports.LABELS_URL = "/labels";
