"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SOMEDAY = exports.DONE = exports.PROMOTE_NOTIFY = exports.UPDATE_WEB_DOC = exports.RELEASED_FREE = exports.RELEASED_PAID = exports.RELEASED_BETA = exports.APPROVED = exports.TESTING_REVIEW = exports.IN_PROGRESS = exports.NEXT = exports.BLOCKED_WAITING = exports.BUGS = exports.SOON = exports.ROCKS = exports.NEEDS_SPEC = exports.RECURRING = exports.INBOX = void 0;
exports.INBOX = "Inbox (new ideas)";
exports.RECURRING = "Recurring";
exports.NEEDS_SPEC = "Needs Spec";
exports.ROCKS = "Rocks";
exports.SOON = "Soon";
exports.BUGS = "Bugs 🙄🙁😦😢😭";
exports.BLOCKED_WAITING = "Blocked / Waiting";
exports.NEXT = "Next";
exports.IN_PROGRESS = "In Progress";
exports.TESTING_REVIEW = "Testing / Review";
exports.APPROVED = "Approved";
exports.RELEASED_BETA = "Released in Beta";
exports.RELEASED_PAID = "Released (paid editions)";
exports.RELEASED_FREE = "Released (free wp.org)";
exports.UPDATE_WEB_DOC = "Update Website/Documentation";
exports.PROMOTE_NOTIFY = "Promote / Notify";
exports.DONE = "Done";
exports.SOMEDAY = "Someday";
